In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import classification_report
from sklearn import metrics
from sklearn import tree

In [2]:
data=pd.read_csv("modified_data.csv")
data

,N,P,K,temperature,humidity,ph,rainfall,label,price
0,90,42,43,20.879744,82.002744,6.502985,202.935536,rice,3480.004533
1,85,58,41,21.770462,80.319644,7.038096,226.655537,rice,3424.723374
2,60,55,44,23.004459,82.320763,7.840207,263.964248,rice,3432.898683
3,74,35,40,26.491096,80.158363,6.980401,242.864034,rice,3384.224015
4,78,42,42,20.130175,81.604873,7.628473,262.717340,rice,3552.363940
...,...,...,...,...,...,...,...,...,...
2195,107,34,32,26.774637,66.413269,6.780064,177.774507,coffee,12886.387652
2196,99,15,27,27.417112,56.636362,6.086922,127.924610,coffee,13087.431602
2197,118,33,30,24.131797,67.225123,6.362608,173.322839,coffee,11942.644131
2198,117,32,34,26.272418,52.127394,6.758793,127.175293,coffee,12201.373090
2199,104,18,30,23.603016,60.396475,6.779833,140.937041,coffee,12875.480821

In [3]:
data.head()

    N   P   K  temperature   humidity        ph    rainfall label        price
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice  3480.004533
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice  3424.723374
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice  3432.898683
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice  3384.224015
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice  3552.363940

In [4]:
data.tail()

,N,P,K,temperature,humidity,ph,rainfall,label,price
2195,107,34,32,26.774637,66.413269,6.780064,177.774507,coffee,12886.387652
2196,99,15,27,27.417112,56.636362,6.086922,127.924610,coffee,13087.431602
2197,118,33,30,24.131797,67.225123,6.362608,173.322839,coffee,11942.644131
2198,117,32,34,26.272418,52.127394,6.758793,127.175293,coffee,12201.373090
2199,104,18,30,23.603016,60.396475,6.779833,140.937041,coffee,12875.480821

In [5]:
data.shape

(2200, 9)

In [6]:
data.columns

Index(['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall', 'label',
       'price'],
      dtype='object')

In [7]:
data.describe()

,N,P,K,temperature,humidity,ph,rainfall,price
count,2200.000000,2200.000000,2200.000000,2200.000000,2200.000000,2200.000000,2200.000000,2200.000000
mean,50.551818,53.362727,48.149091,25.616244,71.481779,6.469480,103.463655,6507.493274
std,36.917334,32.985883,50.647931,5.063749,22.263812,0.773938,54.958389,2789.268977
min,0.000000,5.000000,5.000000,8.825675,14.258040,3.504752,20.211267,1703.278385
25%,21.000000,28.000000,20.000000,22.769375,60.261953,5.971693,64.551686,4615.786485
50%,37.000000,51.000000,32.000000,25.598693,80.473146,6.425045,94.867624,6808.961394
75%,84.250000,68.000000,49.000000,28.561654,89.948771,6.923643,124.267508,8664.695000
max,140.000000,145.000000,205.000000,43.675493,99.981876,9.935091,298.560117,13109.604222

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   N            2200 non-null   int64
 1   P            2200 non-null   int64
 2   K            2200 non-null   int64
 3   temperature  2200 non-null   float64
 4   humidity     2200 non-null   float64
 5   ph           2200 non-null   float64
 6   rainfall     2200 non-null   float64
 7   label        2200 non-null   object
 8   price        2200 non-null   float64
dtypes: float64(5), int64(3), object(1)
memory usage: 154.8+ KB

In [9]:
#types of crops in the dataset
data['label'].unique()

array(['rice', 'maize', 'chickpea', 'kidneybeans', 'pigeonpeas',
       'mothbeans', 'mungbean', 'blackgram', 'lentil', 'pomegranate',
       'banana', 'mango', 'grapes', 'watermelon', 'muskmelon', 'apple',
       'orange', 'papaya', 'coconut', 'cotton', 'jute', 'coffee'],
      dtype=object)

In [10]:
x=data.drop('label',axis=1)
y=data['label']
x

        N   P   K  temperature   humidity        ph    rainfall         price
0      90  42  43    20.879744  82.002744  6.502985  202.935536   3480.004533
1      85  58  41    21.770462  80.319644  7.038096  226.655537   3424.723374
2      60  55  44    23.004459  82.320763  7.840207  263.964248   3432.898683
3      74  35  40    26.491096  80.158363  6.980401  242.864034   3384.224015
4      78  42  42    20.130175  81.604873  7.628473  262.717340   3552.363940
...   ...  ..  ..          ...        ...       ...         ...           ...
2195  107  34  32    26.774637  66.413269  6.780064  177.774507  12886.387652
2196   99  15  27    27.417112  56.636362  6.086922  127.924610  13087.431602
2197  118  33  30    24.131797  67.225123  6.362608  173.322839  11942.644131
2198  117  32  34    26.272418  52.127394  6.758793  127.175293  12201.373090
2199  104  18  30    23.603016  60.396475  6.779833  140.937041  12875.480821

[2200 rows x 8 columns]

In [11]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
scaler.fit(x)
x

        N   P   K  temperature   humidity        ph    rainfall         price
0      90  42  43    20.879744  82.002744  6.502985  202.935536   3480.004533
1      85  58  41    21.770462  80.319644  7.038096  226.655537   3424.723374
2      60  55  44    23.004459  82.320763  7.840207  263.964248   3432.898683
3      74  35  40    26.491096  80.158363  6.980401  242.864034   3384.224015
4      78  42  42    20.130175  81.604873  7.628473  262.717340   3552.363940
...   ...  ..  ..          ...        ...       ...         ...           ...
2195  107  34  32    26.774637  66.413269  6.780064  177.774507  12886.387652
2196   99  15  27    27.417112  56.636362  6.086922  127.924610  13087.431602
2197  118  33  30    24.131797  67.225123  6.362608  173.322839  11942.644131
2198  117  32  34    26.272418  52.127394  6.758793  127.175293  12201.373090
2199  104  18  30    23.603016  60.396475  6.779833  140.937041  12875.480821

[2200 rows x 8 columns]

In [12]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x,y,test_size = 0.2,random_state = None)
xtrain.shape

(1760, 8)

In [13]:
# Defining a dictionary such that key = modelname and value = accuracy of the model
best_model = {}

In [14]:
from sklearn.model_selection import cross_val_score

def cross_val_accuracy(model):
    # This function calculates the mean cross validation accuracy
    score = cross_val_score(model, features, target,cv=5)
    #get the mean of each fold 
    return score.mean() * 100

In [15]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

# Scale the data using StandardScaler
scaler = StandardScaler()
xtrain_scaled = scaler.fit_transform(xtrain)
xtest_scaled = scaler.transform(xtest)

# Create an instance of LogisticRegression
logreg = LogisticRegression(max_iter=20)

# Fit the model to the scaled training data
logreg.fit(xtrain_scaled, ytrain)

# Use the model to make predictions on the test data
ypred = logreg.predict(xtest_scaled)

accuracy = metrics.accuracy_score(ytest, ypred)
print(f"Accuracy: {accuracy}",end='\n\n')

# Adding the model to our dictionary
best_model["Logistic Regression"] = accuracy*100
print(best_model)

Accuracy: 0.9886363636363636

{'Logistic Regression': 98.86363636363636}

C:\Users\rithe\AppData\Roaming\Python\Python39\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [16]:
from sklearn.pipeline import make_pipeline

# Create a pipeline with data scaling and logistic regression
pipeline = make_pipeline(StandardScaler(), LogisticRegression(max_iter=1000))

# Perform cross-validation and calculate accuracy
score = cross_val_score(pipeline, x, y, cv=5, scoring='accuracy')

# Print the cross-validation accuracy scores
print("Cross-Validation Accuracy Scores:", score.mean() * 100)

Cross-Validation Accuracy Scores: 99.22727272727272

In [17]:
from sklearn.tree import DecisionTreeClassifier

DecisionTree = DecisionTreeClassifier(criterion = "entropy",
                                     random_state = None,min_samples_split=2,min_samples_leaf=8,
                                     max_depth = 5)
# Fitting the training set to create a model
DecisionTree.fit(xtrain,ytrain)
# Using test(x) to find y
ypred = DecisionTree.predict(xtest)
# Checking whether the predicted y for test(x) matches actual test(y)
accuracy = metrics.accuracy_score(ypred,ytest)
print(f"Accuracy: {accuracy}",end='\n\n')

# Adding the model to our dictionary
best_model["Decision Tree"] = accuracy*100
print(best_model)

Accuracy: 0.990909090909091

{'Logistic Regression': 98.86363636363636, 'Decision Tree': 99.0909090909091}

In [18]:
from sklearn.ensemble import RandomForestClassifier

RandomForest = RandomForestClassifier(n_estimators=9, max_depth=4,random_state=None)

# Fitting the training set to create a model
RandomForest.fit(xtrain,ytrain)
# Using test(x) to find y
ypred = RandomForest.predict(xtest)

accuracy = metrics.accuracy_score(ypred, ytest)
print(f"Accuracy: {accuracy}",end='\n\n')

# Adding the model to our dictionary
best_model["Random Forest"] = accuracy*100
print(best_model)

Accuracy: 0.8590909090909091

{'Logistic Regression': 98.86363636363636, 'Decision Tree': 99.0909090909091, 'Random Forest': 85.9090909090909}

In [19]:
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import GridSearchCV
from sklearn import metrics

# Define the parameter grid
param_grid = {'var_smoothing': [1e-9, 1e-8, 1e-7, 1e-6, 1e-5]}

# Initialize the Gaussian Naive Bayes model
NaiveBayes = GaussianNB()

# Initialize GridSearchCV with the NaiveBayes model and parameter grid
grid_search = GridSearchCV(NaiveBayes, param_grid, cv=3)

# Fit the training set to create a model
grid_search.fit(xtrain, ytrain)

# Find the best parameters
best_params = grid_search.best_params_

# Use the best model to predict y
ypred = grid_search.predict(xtest)

# Calculate the accuracy
accuracy = metrics.accuracy_score(ypred, ytest)
print(f"Accuracy: {accuracy}\n")

# Adding the model to our dictionary
best_model["Naive Bayes"] = accuracy * 100
print(best_model)

Accuracy: 1.0

{'Logistic Regression': 98.86363636363636, 'Decision Tree': 99.0909090909091, 'Random Forest': 85.9090909090909, 'Naive Bayes': 100.0}

In [20]:
from sklearn.svm import SVC
from sklearn.preprocessing import MinMaxScaler

# fit scaler on training data
norm = MinMaxScaler().fit(xtrain)
x_train_norm = norm.transform(xtrain)
# transform testing dataabs
x_test_norm = norm.transform(xtest)
SVM = SVC(kernel='linear', degree=2, C=1)
SVM.fit(x_train_norm,ytrain)
ypred = SVM.predict(x_test_norm)

accuracy = metrics.accuracy_score(ytest, ypred)
print(f"Accuracy: {accuracy}",end='\n\n')

# Adding the model to our dictionary
best_model["SVM"] = accuracy*100
print(best_model)

Accuracy: 0.9954545454545455

{'Logistic Regression': 98.86363636363636, 'Decision Tree': 99.0909090909091, 'Random Forest': 85.9090909090909, 'Naive Bayes': 100.0, 'SVM': 99.54545454545455}

In [21]:
#!pip install xgboost

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: xgboost in c:\users\rithe\appdata\roaming\python\python39\site-packages (2.1.0)
Requirement already satisfied: numpy in c:\programdata\anaconda3\lib\site-packages (from xgboost) (1.21.5)
Requirement already satisfied: scipy in c:\programdata\anaconda3\lib\site-packages (from xgboost) (1.9.1)

In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.preprocessing import LabelEncoder

# Initialize LabelEncoder
label_encoder = LabelEncoder()

# Fit label encoder on the target labels and transform them
ytrain_encoded = label_encoder.fit_transform(ytrain)
ytest_encoded = label_encoder.transform(ytest)

# Build the model
model = Sequential()
# Shape (None,7)
model.add(Dense(64, activation='relu', input_shape=(8,)))
model.add(Dense(128, activation='relu'))  # Additional layer
  # Additional layer
model.add(Dense(64, activation='relu'))  # Additional layer
model.add(Dense(22, activation='softmax'))

# Compile the model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Define the callback
class AccuracyCallback(keras.callbacks.Callback):
    def on_epoch_end(self, epoch, logs=None):
        if logs.get('accuracy') >= 0.99 and logs.get('val_accuracy') >= 0.99:
            self.model.stop_training = True

# Create an instance of the callback
callback = AccuracyCallback()

# Train the model with the encoded target labels and the callback
model.fit(xtrain_scaled, ytrain_encoded, epochs=100, batch_size=32, validation_data=(xtest_scaled, ytest_encoded), callbacks=[callback])

# Evaluate the model
test_loss, test_acc = model.evaluate(xtest_scaled, ytest_encoded)
print(f"Test Loss: {test_loss}")
print(f"Test Accuracy: {test_acc}")
best_model["NN"] = accuracy*100
print(best_model)

In [ ]:
import xgboost as xgb
from sklearn import metrics
from sklearn.preprocessing import LabelEncoder

# Encode the target variable 'y' into integer labels
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(ytrain)

# Create and fit the XGBoost classifier
XGB = xgb.XGBClassifier()
XGB.fit(xtrain, y_encoded)

# Predict the labels for the test set
ypred = XGB.predict(xtest)

# Decode the predicted labels back to their original string labels
ypred_decoded = label_encoder.inverse_transform(ypred)

# Calculate and print the accuracy
accuracy = metrics.accuracy_score(ytest, ypred_decoded)
print(f"Accuracy: {accuracy}",end='\n\n')

# Adding the model to our dictionary
best_model["XGB"] = accuracy*100
print(best_model)

In [ ]:
accuracies = list(best_model.values())
model_names = list(best_model.keys())

# Create a bar plot using seaborn
sns.barplot(x=accuracies, y=model_names)
plt.xlabel('Model')
plt.ylabel('Accuracy')
plt.title('Model Accuracies')
plt.show()